spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://hackathon-m-rds.ciwy7obdgrgx.ap-northeast-2.rds.amazonaws.com/hackathon_m
    username: ${{ secrets.DATABASE_USERNAME }}
    password: ${{ secrets.DATABASE_PASSWORD }}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl: