spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: newjeans
    password: hk987852!
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

cloud:
  aws:
    s3:
      bucket: image-model-demo
      path:
        upload: upload
    credentials:
      access-key: AKIAVNC7ICKTDWXUFDYG
      secret-key: 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
