spring:
  application:
    name: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hackathon-m-rds.ciwy7obdgrgx.ap-northeast-2.rds.amazonaws.com/hackathon_m
    username: admin
    password: admin123

  #    url: jdbc:mysql://localhost:3306/hackathon_m
  #    username: root
  #    password: 1108
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update

cloud:
  aws:
    s3:
      bucket: image-model-demo
      path:
        upload: upload
    credentials:
      access-key: AKIAVNC7ICKTGD3BG6GQ
      secret-key: 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