name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker build -t app .
          docker tag app ${{ secrets.DOCKERHUB_USERNAME }}/hackathonm:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hackathonm:latest

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}

          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hackathonm:latest
            sudo docker run --name hackathonm -d -p 8080:8080 -e ${{ secrets.DOCKERHUB_USERNAME }}/hackathonm:latest